### ISSUE TITLE
Clean up listeners with Beta 4 widget-core

### ISSUE THREAD

**Issue by kitsonk** [dojo/web-editor#30]
In #27 we are introducing some listeners, there aren't clean lifecycle methods in the 0.1.0 widget-core to clean those up, but in 0.2.0 there are, so we should ensure we add and remove the work bench listeners on the new lifecycle methods.

**Comment by agubler** [comment]
In widget-core 0.1.0, you can still leverage `destroy` for references that need to be cleaned up - As you mention in beta4 this is best handled in the `onDetach` lifecycle hook.
